### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by mpelleau** [mpelleau/AbSolute#3]
- [ ] add vpl
 - [ ] add integers
 - [ ]  add reduced product between box and vpl
 - [ ]  add test
 - [ ]  fix bug with non box abstract domain
 - [ ]  build opam package

**Comment by mpelleau** [comment]
- [ ] find out how to deal with unconstrained variables
 - [ ] add special comments for api generation
 - [ ] pruning for reduced product
